easy_healthcare/academic_feedback_sys/urls.py
from django.urls import path
from . import views, views_2, views_3


app_name = "academic_feedback_sys"

urlpatterns = [
    # AUTH PAGE
    path("my_login/", views.CustomLoginView.as_view(), name="my_login"),
    path("my_logout/", views.custom_logout, name="my_logout"),
    # MAIN LANDING PAGE
    path("dashboard/", views_3.DashBoard, name="dashboard"),
    # TEACHER PATHS
    path("teacherhome/", views.TeacherHome, name="staff"),
    path("teacherprofile/", views.TeacherProfile, name="profile"),
    path("teacherstudents/", views.TeacherStudents, name="students"),
    path("teacherrecentgraded/", views.TeacherRecentGraded, name="recent_grades"),
    path("teachereditstudent/<str:first_name>/<str:middle_name>/<str:last_name>/", views.TeacherEditStudentGrade, name="edit_student_grade"),
    # PARENT PATHS
    path("parentguardianplatform/", views_2.ParentLoginPlatform, name="parent_login"),
    path("parentguardianreport/<uuid:password>/", views_2.ParentReport, name="report"),
    path("parentguardiansuccess/", views_2.ParentReportSuccess, name="report_success"),
]

easy_healthcare/easy_healthcare/urls.py
import os
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("healthpass/", include("healthpass.urls", namespace="health")),
    path("academic_feedback_sys/", include("academic_feedback_sys.urls", namespace="academic")),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Add the custom error handler view to the handlers
# handler500 = "healthpass.views5.custom_error_500"
# handler404 = "healthpass.views5.custom_error_404"
# handler403 = "healthpass.views5.custom_error_403"
# handler400 = "healthpass.views5.custom_error_400"
handler403 = "academic_feedback_sys.views.custom_error_403"

easy_healthcare/healthpass/urls.py
from django.urls import path
from . import views
from . import views2
from . import views3
from . import views4

app_name = "healthpass"
urlpatterns = [
    # authentication paths
    path("user_signup/", views2.UserSignUp.as_view(), name="user_signup"),
    path("user_home/", views2.UserHome.as_view(), name="user_home"),
    path("user_logout/", views2.UserLogOut.as_view(), name="user_logout"),
    path("custom_signup/", views.CustomSignUp.as_view(), name="custom_signup"),
    path("custom_login/", views.CustomLogin.as_view(template_name="healthpass/custom_login.html"), name="custom_login"),
    path("custom_home/", views.CustomHome.as_view(), name="custom_home"),
    path("custom_logout/", views.CustomLogout.as_view(), name="custom_logout"),
    path("custom_ban/", views.CustomBan.as_view(), name="custom_ban"),
    path("custom_password_reset/", views.CustomPasswordReset.as_view(), name="custom_password_reset"),
    path("custom_password_reset_done/", views.CustomPasswordResetDone.as_view(), name="custom_password_reset_done"),
    path("custom_reset/<str:uidb64>/<str:token>/", views.CustomReset.as_view(), name="custom_reset"),
    path("custom_reset_done/", views.CustomResetDone.as_view(), name="custom_reset_done"),
    path("custom_password_reset_warning/", views.CustomPasswordResetWarning.as_view(), name="custom_password_reset_warning"),

    # blood work paths
    path("blood_work_create/", views3.BloodWorkCreateView.as_view(), name="blood_work_create"),
    path("blood_work_read/", views3.BloodWorkListView.as_view(), name="blood_work_read"),
    path("blood_work_read_update/", views3.BloodWorkUpdateListView.as_view(), name="blood_work_read_update"),
    path("blood_work_update/<int:pk>/", views3.BloodWorkUpdateView.as_view(), name="blood_work_update"),
    path("blood_work_read_delete/", views3.BloodWorkDeleteListView.as_view(), name="blood_work_read_delete"),
    path("blood_work_delete/<int:pk>/", views3.BloodWorkDeleteView.as_view(), name="blood_work_delete"),
    # general info paths
    path("general_info_create/", views3.GeneralInfoCreateView.as_view(), name="general_info_create"),
    path("general_info_read/", views3.GeneralInfoListView.as_view(), name="general_info_read"),
    path("general_info_read_update/", views3.GeneralInfoUpdateListView.as_view(), name="general_info_read_update"),
    path("general_info_update/<int:pk>/", views3.GeneralInfoUpdateView.as_view(), name="general_info_update"),
    path("general_info_read_delete/", views3.GeneralInfoDeleteListView.as_view(), name="general_info_read_delete"),
    path("general_info_delete/<int:pk>/", views3.GeneralInfoDeleteView.as_view(), name="general_info_delete"),
    # urinalysis paths
    path("urinalysis_create/", views3.UrinalysisCreateView.as_view(), name="urinalysis_create"),
    path("urinalysis_read/", views3.UrinalysisListView.as_view(), name="urinalysis_read"),
    path("urinalysis_read_update/", views3.UrinalysisUpdateListView.as_view(), name="urinalysis_read_update"),
    path("urinalysis_update/<int:pk>/", views3.UrinalysisUpdateView.as_view(), name="urinalysis_update"),
    path("urinalysis_read_delete/", views3.UrinalysisDeleteListView.as_view(), name="urinalysis_read_delete"),
    path("urinalysis_delete/<int:pk>/", views3.UrinalysisDeleteView.as_view(), name="urinalysis_delete"),
    # custom blood work read, urinalysis read, and general info read
    path("custom_blood_work_read/", views4.CustomBloodWorkListView.as_view(), name="custom_blood_work_read"),
    path("custom_general_info_read/", views4.CustomGeneralInfoListView.as_view(), name="custom_general_info_read"),
    path("custom_urinalysis_read/", views4.CustomUrinalysisListView.as_view(), name="custom_urinalysis_read"),
]

easy_healthcare/academic_feedback_sys/forms.py
from django.forms import ModelForm
from .models import ClassLevel, Semester, Subject, Score

class ClassLevelForm(ModelForm):
    class Meta:
        model = ClassLevel
        fields = "__all__"

class SemesterForm(ModelForm):
    class Meta:
        model = Semester
        fields = "__all__"

class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = "__all__"

class ScoreForm(ModelForm):
    class Meta:
        model = Score
        fields = "__all__"

easy_healthcare/academic_feedback_sys/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import logout
from django.urls import reverse
from django.utils.http import urlencode
from guardian.models import UserObjectPermission
from .models import Student, ClassLevel, Score, Semester, Grade, Subject
from .forms import ClassLevelForm, SemesterForm, SubjectForm, ScoreForm
import datetime
# Create your views here.

# global utility variables
cookie_time = 60 * 60 * 3
access_denied_error_template = "academic_feedback_sys/no_permission.html"

# global utility functions
def set_view_cookies(view_request):
    login_url = reverse('academic:my_login') + '?' + urlencode({"next": view_request.path})
    redirect_login_response = redirect(login_url)
    redirect_login_response.set_cookie("session-cookie", "short-cookie")
    redirect_login_response.set_cookie("timed-cookie", "long-cookie", max_age=cookie_time)
    return redirect_login_response

# Custom Error Views
def custom_error_403(request, exception=None):
    return render(request, access_denied_error_template, status=403)


# define custom_login view
class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

    def get_success_url(self):
        # Check if the 'next' parameter is present in the URL
        next_url = self.get_redirect_url()
        if next_url:
            print(next_url)
            return next_url
        # Otherwise return teacher home page from normal login action
        return reverse('academic:staff')

# define custom_logout view
def custom_logout(request):
    logout(request)
    return redirect("academic:my_login")

# Teacher Views
@login_required(login_url="/academic_feedback_sys/my_login/")
def TeacherHome(request):
    template_name = "academic_feedback_sys/teacher_home.html"
    # check cookies even though the user is logged in from a previous session
    # if any of the cookie has expired first logout the user.
    # and the redirect to the login page with a next parameter
    # add cookies and return the response
    if not request.COOKIES.get("session-cookie", None) or not request.COOKIES.get("timed-cookie", None):
        logout(request)
        redirect_login_response = set_view_cookies(request)
        return redirect_login_response
    # now check if this user is a staff because some people can create healthpass login
    # and would want to login
    if request.user.is_staff == True:
        # create a context saving the teacher's object
        # can be gotten from request object easily
        # then return a response from the render object
        context_variable = {}
        logged_teacher_obj = request.user
        context_variable["logged_teacher_obj"] = logged_teacher_obj
        return render(request, template_name, context_variable)
    # if the user isn't a staff send the person to a 403 error page
    # TODO later, but for now just pass
    raise PermissionDenied

@login_required(login_url="/academic_feedback_sys/my_login/")
def TeacherProfile(request):
    template_name = "academic_feedback_sys/teacher_profile.html"
    # check cookies even though the user is logged in from a previous session
    # if any of the cookie has expired first logout the user.
    # and the redirect to the login page with a next parameter
    # add cookies and return the response
    if not request.COOKIES.get("session-cookie", None) or not request.COOKIES.get("timed-cookie", None):
        logout(request)
        redirect_login_response = set_view_cookies(request)
        return redirect_login_response
    if request.user.is_staff == True:
        # create a context saving the teacher's object
        # can be gotten from request object easily
        # then return a response from the render object
        context_variable = {}
        logged_teacher_obj = request.user
        context_variable["logged_teacher_obj"] = logged_teacher_obj
        return render(request, template_name, context_variable)
    # if the user isn't a staff send the person to a 403 error page
    # TODO later, but for now just pass
    raise PermissionDenied

@login_required(login_url="/academic_feedback_sys/my_login/")
def TeacherStudents(request):
    template_name = "academic_feedback_sys/teacher_students.html"
    # check cookies even though the user is logged in from a previous session
    # if any of the cookie has expired first logout the user.
    # and the redirect to the login page with a next parameter
    # add cookies and return the response
    if not request.COOKIES.get("session-cookie", None) or not request.COOKIES.get("timed-cookie", None):
        logout(request)
        redirect_login_response = set_view_cookies(request)
        return redirect_login_response
    # now check if this user is a staff because some people can create healthpass login
    # and would want to login to this app
    if request.user.is_staff == True:
        # create a context variable to store all students
        # of that class teacher and a id integer list
        # to store the student id's
        id_list = None
        context_variable = {}
        class_teacher = request.user
        # get the class teacher student, based on permission
        # this returns a row of the student(s) that the class
        # teacher as permission to edit their grade
        # but not exactly the students but we have an information
        # we need in those rows i.e the object_pk which is the
        # student primary key i.e id in string
        class_teacher_perm_students = UserObjectPermission.objects.filter(user=class_teacher).all()
        # extract all ids in strings and convert to integers
        # using list comprehension
        id_list = [int(row.object_pk) for row in class_teacher_perm_students]
        # then get all student objects now using this id list
        class_teacher_students = Student.objects.filter(id__in=id_list)
        # now I have all student we can now store it in the context variable
        # and also store class teacher object
        context_variable["class_teacher"] = class_teacher
        context_variable['students'] = class_teacher_students
        return render(request, template_name, context_variable)
    raise PermissionDenied

@login_required(login_url="/academic_feedback_sys/my_login/")
def TeacherRecentGraded(request):
    template_name = "academic_feedback_sys/teacher_recent_grades.html"
    # check cookies even though the user is logged in from a previous session
    # if any of the cookie has expired first logout the user.
    # and the redirect to the login page with a next parameter
    # add cookies and return the response
    if not request.COOKIES.get("session-cookie", None) or not request.COOKIES.get("timed-cookie", None):
        logout(request)
        redirect_login_response = set_view_cookies(request)
        return redirect_login_response
    # now check if this user is a staff because some people can create healthpass login
    # and would want to login to this app
    if request.user.is_staff == True:
        # create a context variable to store all students
        # of that class teacher and a id integer list
        # to store the student id's
        id_list = None
        context_variable = {}
        class_teacher = request.user
        # get the class teacher student, based on permission
        # this returns a row of the student(s) that the class
        # teacher as permission to edit their grade
        # but not exactly the students but we have an information
        # we need in those rows i.e the object_pk which is the
        # student primary key i.e id in string
        class_teacher_perm_students = UserObjectPermission.objects.filter(user=class_teacher).all()
        # extract all ids in strings and convert to integers
        # using list comprehension
        id_list = [int(row.object_pk) for row in class_teacher_perm_students]
        # then get all student objects now using this id list
        class_teacher_students = Student.objects.filter(id__in=id_list)
        # get the class teacher student grades that are filteres for this
        # particular year, for these students, ordered by semester, semester_year__month
        # and semester_year__day in descending order
        current_date = datetime.datetime.now()
        current_year = current_date.year
        recent_grades = Grade.objects.filter(
            student__in=class_teacher_students,
            semester_year__year=current_year,
        ).order_by("-semester", "-semester_year__month", "-semester_year__day")
        context_variable["recent_grades"] = recent_grades

        return render(request, template_name, context_variable)
    
    raise PermissionDenied

@login_required(login_url="/academic_feedback_sys/my_login/")
def TeacherEditStudentGrade(request, first_name, middle_name, last_name):
    template_name = "academic_feedback_sys/teacher_edit_student_grade.html"
    error_template = "academic_feedback_sys/no_edit_permission.html"
    if request.method == "GET":
        # check cookies even though the user is logged in from a previous session
        # if any of the cookie has expired first logout the user.
        # and the redirect to the login page with a next parameter
        # add cookies and return the response
        if not request.COOKIES.get("session-cookie", None) or not request.COOKIES.get("timed-cookie", None):
            logout(request)
            redirect_login_response = set_view_cookies(request)
            return redirect_login_response
        # now check if this user is a staff because some people can create healthpass login
        # and would want to login
        if request.user.is_staff == True:
            # Take the first_name, middle_name, and last_name to get the student
            # object clicked on, then first check if the student exists

easy_healthcare/academic_feedback_sys/templates/academic_feedback_sys/no_report_view_permission.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error - Permission Denied</title>
    <link rel="icon" href="https://i.ibb.co/gDmm74W/academic-feedback-logo.png" type="image/png">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

        * {
            font-family: "Poppins", sans-serif;
            font-weight: 400;
            font-style: normal;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            text-align: center;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 40px 60px;
            max-width: 600px;
        }

        h1 {
            color: #FF6347;
            font-size: 36px;
        }

        p {
            color: #555555;
            font-size: 18px;
            line-height: 1.6;
        }

        .button {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #FF6347;
            color: #ffffff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #e5533d;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>403 - No Report View Permission</h1>
        <p>We're sorry, but the page you requested you are not allowed to view.</p>
        <p>Please check the URL and try again or go back to the Login page.</p>
        <a href="{% url 'academic:parent_login' %}" class="button">Back to Login</a>
    </div>
</body>

</html>

easy_healthcare/academic_feedback_sys/templates/academic_feedback_sys/parent_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './styles/parent_login.css' %}">
    <link rel="icon" href="https://i.ibb.co/gDmm74W/academic-feedback-logo.png" type="image/png">
    <title>Document</title>
</head>
<body>
    {% load crispy_forms_tags %}
    <main>
        {% if error_message %}
            <div class="Error">
                <p>{{error_message}}</p>
            </div>
        {% endif %}
        <div class="form-div">
            <div class="header-div">
                <h1>Login to Parent's Portal</h1>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="wrapper">
                    <div class="input-data">
                        {{parent_form.first_name}}
                        <div class="underline"></div>
                        {{parent_form.first_name.label_tag}}
                    </div>
                </div>
                <div class="wrapper">
                    <div class="input-data">
                        {{parent_form.middle_name}}
                        <div class="underline"></div>
                        {{parent_form.middle_name.label_tag}}
                    </div>
                </div>
                <div class="wrapper">
                    <div class="input-data">
                        {{parent_form.last_name}}
                        <div class="underline"></div>
                        {{parent_form.last_name.label_tag}}
                    </div>
                </div>
                <div class="wrapper">
                    <div class="input-data">
                        {{parent_form.password}}
                        <div class="underline"></div>
                        {{parent_form.password.label_tag}}
                    </div>
                </div>
                <div class=" wrapper button">
                    <button type="submit" class="submit">
                        <span class="submit__text">Login</span>
                        <span class="submit__icon">
                            <ion-icon name="log-in-outline"></ion-icon>
                        </span>
                    </button>
                </div>
                <div class="button-div" style="color:blue; display: flex; justify-content: center; margin-top: 1rem;">
                    <div class="dummy-div"></div>
                    <a href="{% url 'academic:dashboard' %}" style="text-decoration:none; display: flex; justify-content: center; align-items: center; width: 100px; height: 30px; border: 2px solid black; border-radius: 5px; background: white"><span>dasboard</span></a>
                <div>
            </form>
        </div>
    </main>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
</body>
</html>

easy_healthcare/academic_feedback_sys/templates/academic_feedback_sys/parent_report_success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Confirmation</title>
    <link rel="icon" href="https://i.ibb.co/gDmm74W/academic-feedback-logo.png" type="image/png">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

        * {
            font-family: "Poppins", sans-serif;
            font-weight: 400;
            font-style: normal;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px 40px;
            max-width: 500px;
            text-align: center;
        }

        h1 {
            color: #4CAF50;
            font-size: 24px;
        }

        p {
            color: #555555;
            font-size: 16px;
            line-height: 1.5;
        }

        .button {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: #ffffff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Email Confirmation Sent</h1>
        <p>Thank you! A confirmation email has been sent. Please check your email to view the student's report.</p>
        <p>If you don't receive the email within a few minutes, please check your spam folder or try again.</p>
        <a href="{% url 'academic:parent_login' %}" class="button">Back to Login</a>
    </div>
</body>

</html>

easy_healthcare/academic_feedback_sys/templates/academic_feedback_sys/teacher_edit_student_grade.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Student Grade</title>
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static './styles/teacher_edit_student_grade.css' %}">
    <link rel="icon" href="https://i.ibb.co/gDmm74W/academic-feedback-logo.png" type="image/png">
</head>
<body>
    <div class="homepage">
        <a href="{% url 'academic:students' %}" class="staff">Back</a>
    </div>
    {% if duplicate_subject_error %}
        <div class="error">
            <div class="empty"></div>
            <div class="error-text">{{duplicate_subject_error}}</div>
        </div>
    {% endif %}
    {% if success_message %}
        <div class="success">
            <div class="empty"></div>
            <div class="success-text">{{success_message}}</div>
        </div>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-flex">
            <div>
                <label for="first_name">first name:</label>
                <input id="first_name" type="text" name="first_name" value="{{first_name}}" placeholder="Enter first name">
            </div>
            <div>
                <label for="middle_name">middle name:</label>
                <input id="middle_name" type="text" name="middle_name" value="{{middle_name}}" placeholder="Enter middle name">
            </div>
            <div>
                <label for="last_name">last name:</label>
                <input id="last_name" type="text" name="last_name" value="{{last_name}}" placeholder="Enter last name">
            </div>
            {{class_level_form.as_div}}
            {{semester_form.as_div}}
            {% for subject_name, subject_form in subjects.items %}
                <div>
                    <label for="{{subject_name}}">{{subject_name}}</label>
                    {{subject_form}}
                </div>
                {% for score_name, score_form in scores.items %}
                    {% if forloop.counter == forloop.parentloop.counter %}
                        <div>
                            <label for="{{score_name}}">{{score_name}}</label>
                            {{score_form}}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <div>
                <button type="submit" class="submit">
                    <span class="submit__text">Add Grade</span>
                    <span class="submit__icon">
                        <ion-icon name="send-outline"></ion-icon>
                    </span>
                </button>
            </div>
        </div>
    </form>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
</body>
</html>

easy_healthcare/academic_feedback_sys/templates/academic_feedback_sys/teacher_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static './styles/teacher_home.css' %}">
    <link rel="icon" href="https://i.ibb.co/gDmm74W/academic-feedback-logo.png" type="image/png">
    <title>{{logged_teacher_obj.first_name}} Page</title>
</head>

<body>
    <header>
        <div class="name">
            <p>Hello {{logged_teacher_obj.first_name}} {{logged_teacher_obj.last_name}} Welcome.</p>
        </div>
        <div class="logout">
            <button>
                <a href="{% url 'academic:my_logout' %}">Logout</a>
            </button>
        </div>
    </header>
    <section class="sections first-color">
        <div class="odd-div section-div div-display1">
            <a href="{% url 'academic:profile' %}">
                Profile
                <p>This section displays information about the teacher's profile.</p>
                <p>It typically includes details such as the teacher's name, email address, department, and role within
                    the school or institution.</p>
                <p>Clicking on any part of this section might lead to the teacher's profile page, where more detailed information about the teacher can be viewed</p>
            </a>
        </div>
        <div class="curve"></div>
    </section>
    <section class="sections second-color">
        <div class="even-div section-div div-display2">
            <a href="{% url 'academic:students' %}">
                Students
                <p>This section lists the students associated with the teacher's account.</p>
                <p>It contains a list of student names and subject teachers of that student, allowing the class teacher to quickly access information about their students.</p>
                <p>Clicking on a student section leads to a detailed list of student, where the teacher can update grades</p>
            </a>
        </div>
    </section>
    <section class="sections third-color">
        <div class="odd-div section-div div-display1">
            <a href="{% url 'academic:recent_grades' %}">
                Recently Graded
                <p>This section provides a summary of recently graded students</p>
                <p>It includes the names of the graded students</p>
                <p>Clicking or hovering on a student name leads to a detailed info of the student recently grade</p>
            </a>
        </div>
    </section>
    <section class="sections fourth-color">
        <div class="even-div section-div div-display2">
            <h3>African Leadership University</h3>
            <p>123 Main Street, Cityville, Country</p>
            <p>Phone: +123 456 7890</p>
            <p>Email: info@alueducation.com</p>
            <p>Website: <a href="https://www.alueducation.com">www.alueducation.com</a></p>
            <p>Follow us on social media:</p>
            <div class="social-media">
                <span><a href="https://www.facebook.com/ALUeducation"><i class="fab fa-facebook-f"></i></a></span>
                <span><a href="https://twitter.com/ALUeducation"><i class="fab fa-twitter"></i></a></span>
                <span><a href="https://www.linkedin.com/company/african-leadership-university/"><i
                            class="fab fa-linkedin-in"></i></a></span>
                <span><a href="https://www.instagram.com/ALUeducation"><i class="fab fa-instagram"></i></a></span>
            </div>
        </div>
        <div class="third-color-wave">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
            </svg>
        </div>
    </section>
</body>
<script src="{% static './scripts/teacher_home.js' %}"></script>
</html>