easy_healthcare/easy_healthcare/urls.py
import os
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("healthpass/", include("healthpass.urls", namespace="health")),
    path("academic_feedback_sys/", include("academic_feedback_sys.urls", namespace="academic")),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Add the custom error handler view to the handlers
# handler500 = "healthpass.views5.custom_error_500"
# handler404 = "healthpass.views5.custom_error_404"
# handler403 = "healthpass.views5.custom_error_403"
# handler400 = "healthpass.views5.custom_error_400"
handler403 = "academic_feedback_sys.views.custom_error_403"

easy_healthcare/healthpass/urls.py
from django.urls import path
from . import views
from . import views2
from . import views3
from . import views4

app_name = "healthpass"
urlpatterns = [
    # authentication paths
    path("user_signup/", views2.UserSignUp.as_view(), name="user_signup"),
    path("user_home/", views2.UserHome.as_view(), name="user_home"),
    path("user_logout/", views2.UserLogOut.as_view(), name="user_logout"),
    path("custom_signup/", views.CustomSignUp.as_view(), name="custom_signup"),
    path("custom_login/", views.CustomLogin.as_view(template_name="healthpass/custom_login.html"), name="custom_login"),
    path("custom_home/", views.CustomHome.as_view(), name="custom_home"),
    path("custom_logout/", views.CustomLogout.as_view(), name="custom_logout"),
    path("custom_ban/", views.CustomBan.as_view(), name="custom_ban"),
    path("custom_password_reset/", views.CustomPasswordReset.as_view(), name="custom_password_reset"),
    path("custom_password_reset_done/", views.CustomPasswordResetDone.as_view(), name="custom_password_reset_done"),
    path("custom_reset/<str:uidb64>/<str:token>/", views.CustomReset.as_view(), name="custom_reset"),
    path("custom_reset_done/", views.CustomResetDone.as_view(), name="custom_reset_done"),
    path("custom_password_reset_warning/", views.CustomPasswordResetWarning.as_view(), name="custom_password_reset_warning"),

    # blood work paths
    path("blood_work_create/", views3.BloodWorkCreateView.as_view(), name="blood_work_create"),
    path("blood_work_read/", views3.BloodWorkListView.as_view(), name="blood_work_read"),
    path("blood_work_read_update/", views3.BloodWorkUpdateListView.as_view(), name="blood_work_read_update"),
    path("blood_work_update/<int:pk>/", views3.BloodWorkUpdateView.as_view(), name="blood_work_update"),
    path("blood_work_read_delete/", views3.BloodWorkDeleteListView.as_view(), name="blood_work_read_delete"),
    path("blood_work_delete/<int:pk>/", views3.BloodWorkDeleteView.as_view(), name="blood_work_delete"),
    # general info paths
    path("general_info_create/", views3.GeneralInfoCreateView.as_view(), name="general_info_create"),
    path("general_info_read/", views3.GeneralInfoListView.as_view(), name="general_info_read"),
    path("general_info_read_update/", views3.GeneralInfoUpdateListView.as_view(), name="general_info_read_update"),
    path("general_info_update/<int:pk>/", views3.GeneralInfoUpdateView.as_view(), name="general_info_update"),
    path("general_info_read_delete/", views3.GeneralInfoDeleteListView.as_view(), name="general_info_read_delete"),
    path("general_info_delete/<int:pk>/", views3.GeneralInfoDeleteView.as_view(), name="general_info_delete"),
    # urinalysis paths
    path("urinalysis_create/", views3.UrinalysisCreateView.as_view(), name="urinalysis_create"),
    path("urinalysis_read/", views3.UrinalysisListView.as_view(), name="urinalysis_read"),
    path("urinalysis_read_update/", views3.UrinalysisUpdateListView.as_view(), name="urinalysis_read_update"),
    path("urinalysis_update/<int:pk>/", views3.UrinalysisUpdateView.as_view(), name="urinalysis_update"),
    path("urinalysis_read_delete/", views3.UrinalysisDeleteListView.as_view(), name="urinalysis_read_delete"),
    path("urinalysis_delete/<int:pk>/", views3.UrinalysisDeleteView.as_view(), name="urinalysis_delete"),
    # custom blood work read, urinalysis read, and general info read
    path("custom_blood_work_read/", views4.CustomBloodWorkListView.as_view(), name="custom_blood_work_read"),
    path("custom_general_info_read/", views4.CustomGeneralInfoListView.as_view(), name="custom_general_info_read"),
    path("custom_urinalysis_read/", views4.CustomUrinalysisListView.as_view(), name="custom_urinalysis_read"),
]

easy_healthcare/healthpass/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from datetime import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.
class CustomUser(AbstractUser):
    # overwrite the first_name, last_name, and email field
    first_name = models.CharField(max_length=300, blank=False)
    last_name = models.CharField(max_length=300, blank=False)
    email = models.EmailField(blank=False, unique=True)

    # Define groups and user_permissions with unique related_name arguments
    groups = models.ManyToManyField('auth.Group', related_name='custom_user_groups')
    user_permissions = models.ManyToManyField('auth.Permission', related_name='custom_user_permissions')


"""BloodWork and Info utility function"""

def user_directory_path(instance, filename):
    # file will be uploaded to
    # MEDIA_ROOT/photos/user_<id>/%Y/%m/%d/<filename>
    now = datetime.now()
    date_str = now.strftime("%Y/%m/%d")
    return "photos/user_{0}/{1}/{2}".format(instance.owner.id, date_str, filename)

class HbGenotype(models.Model):
    HAEMOGLOBIN_CHOICES = [
        ("AA", "no_haemoglobin_disorder"),
        ("AS", "sickle_cell_trait"),
        ("SS", "sickle_cell_disease"),
        ("SC", "sickle_cell_haemoglobin_c_disease"),
        ("CC", "haemoglobin_c_disease"),
        ("AC", "sickle_cell_mutation"),
    ]
    hb_genotype = models.CharField(
        max_length=2,
        choices=HAEMOGLOBIN_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.hb_genotype)

class SicklingTest(models.Model):
    SICKLING_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    sickling_test = models.CharField(
        max_length=3,
        choices=SICKLING_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.sickling_test)

class BloodGroup(models.Model):
    BLOOD_GROUP_CHOICES = [
        ("AA", "blood_type_A"),
        ("AO", "blood_type_A+o"),
        ("BB", "blood_type_B"),
        ("BO", "blood_type_B+o"),
        ("AB", "blood_type_AB"),
        ("OO", "blood_type_O"),
    ]
    blood_group = models.CharField(
        max_length=2,
        choices=BLOOD_GROUP_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.blood_group)

class MalariaParasite(models.Model):
    MALARIA_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    malaria_parasite = models.CharField(
        max_length=3,
        choices=MALARIA_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.malaria_parasite)

class HepatitisA(models.Model):
    HEPATITIS_A_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    hepatitis_a = models.CharField(
        max_length=3,
        choices=HEPATITIS_A_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.hepatitis_a)

class HepatitisB(models.Model):
    HEPATITIS_B_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    hepatitis_b = models.CharField(
        max_length=3,
        choices=HEPATITIS_B_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.hepatitis_b)

class HIV(models.Model):
    HIV_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    hiv = models.CharField(
        max_length=3,
        choices=HIV_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.hiv)

class VDRL(models.Model):
    VDRL_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    vdrl = models.CharField(
        max_length=3,
        choices=VDRL_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.vdrl)

class HPYLORI(models.Model):
    HPYLORI_CHOICES = [
        ("yes", "positive"),
        ("no", "negative"),
    ]
    hpylori = models.CharField(
        max_length=3,
        choices=HPYLORI_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.hpylori)

class RhesusAntigen(models.Model):
    RH_ANTIGEN_CHOICES = [
        ("A+", "rhesus_positve_a"),
        ("A-", "rhesus_negative_a"),
        ("B+", "rhesus_positive_b"),
        ("B-", "rhesus_negative_b"),
        ("AB+", "rhesus_positive_ab"),
        ("AB-", "rhesus_negative_ab"),
        ("O+", "rhesus_positive_o"),
        ("O-", "rhesus_negative_o"),
    ]
    rhesus_antigen = models.CharField(
        max_length=3,
        choices=RH_ANTIGEN_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.rhesus_antigen)

class BloodWork(models.Model):
    owner = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="owner_blood_work",
    )
    hb_genotype = models.ForeignKey(
        HbGenotype,
        on_delete=models.SET_NULL,
        null=True,
        related_name="hb_genotype_blood_work",
    )
    sickling_test = models.ForeignKey(
        SicklingTest,
        on_delete=models.SET_NULL,
        null=True,
        related_name="sickling_test_blood_work",
    )
    blood_group = models.ForeignKey(
        BloodGroup,
        on_delete=models.SET_NULL,
        null=True,
        related_name="blood_group_blood_work",
    )
    malaria_parasite = models.ForeignKey(
        MalariaParasite,
        on_delete=models.SET_NULL,
        null=True,
        related_name="malaria_parasite_blood_work",
    )
    hepatitis_a = models.ForeignKey(
        HepatitisA,
        on_delete=models.SET_NULL,
        null=True,
        related_name="hepatitis_a_blood_work",
    )
    hepatitis_b = models.ForeignKey(
        HepatitisB,
        on_delete=models.SET_NULL,
        null=True,
        related_name="hepatitis_b_blood_work",
    )
    hiv = models.ForeignKey(
        HIV,
        on_delete=models.SET_NULL,
        null=True,
        related_name="hiv_blood_work",
    )
    vdrl = models.ForeignKey(
        VDRL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="vdrl_blood_work",
    )
    hpylori = models.ForeignKey(
        HPYLORI,
        on_delete=models.SET_NULL,
        null=True,
        related_name="hpylori_blood_work",
    )
    rhesus_antigen = models.ForeignKey(
        RhesusAntigen,
        on_delete=models.SET_NULL,
        null=True,
        related_name="rhesus_antigen_blood_work",
    )
    blood_work_image_file = models.FileField(
        upload_to=user_directory_path,
    )


"""General Info"""

class Gender(models.Model):
    GENDER_CHOICES = [
        ("M", "Male"),
        ("F", "Female"),
    ]
    gender = models.CharField(
        max_length=5,
        choices=GENDER_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.gender)

class Relationship(models.Model):
    RELATIONSHIP_CHOICES = [
        ("Grandfather", "GF"),
        ("Grandmother", "GM"),
        ("Father", "F"),
        ("Mother", "M"),
        ("Uncle", "U"),
        ("Aunt", "A"),
        ("Son", "S"),
        ("Daughter", "D"),
        ("Grandson", "GS"),
        ("Granddaughter", "GD"),
        ("Brother", "BRO"),
        ("Sister", "SIS"),
        ("Cousin", "C"),
        ("Nephew", "N"),
        ("Niece", "NC"),
    ]
    relationship = models.CharField(
        max_length=50,
        choices=RELATIONSHIP_CHOICES,
        unique=True,
    )

    def __str__(self):
        return "{0}".format(self.relationship)

class Immunization(models.Model):
    IMMUNIZATION_CHOICES = [
        ("Hepatitis B", "HEPB"),
        ("Diphtheria, Tetanus, and Whooping Cough(Pertussis)", "DTAP"),
        ("Haemophilus Influenzae Type B", "HIB"),
        ("Polio", "IPV"),
        ("Pneumococcal", "PCV"),
        ("Rotavirus", "RV"),
        ("Influenza", "FLU"),
        ("Chickenpox", "VARICELLA"),
        ("Measles, Mumps, Rubella", "MMR"),
        ("Hepatitis A", "HEPA"),
        ("Human Papillomavirus", "HPV"),
        ("Meningococcal Conjugate", "MENACWY"),
        ("Serogroup B Meningococcal", "MENB"),
        ("Pentavalent", "MENABCWY"),
        ("Shingles", "ZOSTER"),
    ]
    immunization = models.CharField(
        max_length=300,
        choices=IMMUNIZATION_CHOICES,
        unique=True,
    )
    
    def __str__(self):
        return "{0}".format(self.immunization)

class Allergy(models.Model):
    ALLERGY_CHOICES = [
        ("Balsam of Peru", "Balsam of Peru"),
        ("Buckwheat", "Buckwheat"),
        ("Celery", "Celery"),
        ("Egg", "Egg"),
        ("Fish", "Fish"),
        ("Fruit", "Fruit"),
        ("Garlic", "Garlic"),
        ("Oats", "Oats"),
        ("Maize", "Maize"),
        ("Milk", "Milk"),
        ("Mustard", "Mustard"),
        ("Peanut", "Peanut"),
        ("Poultry Meat", "Poultry Meat"),
        ("Red Meat", "Red Meat"),
        ("Rice", "Rice"),
        ("Sesame", "Sesame"),
        ("Shellfish", "Shellfish"),
        ("Soy", "Soy"),
        ("Sulfites", "Sulfites"),
        ("Tartrazine", "Tartrazine"),
        ("Tree nut", "Tree nut"),
        ("Wheat", "Wheat"),
        ("Tetracycline", "Tetracycline"),
        ("Dilantin", "Dilantin"),
        ("Tegretol", "Tegretol"),
        ("Penicillin", "Penicillin"),
        ("Cephalosporins", "Cephalosporins"),
        ("Sulfonamides", "Sulfonamides"),
        ("Non-steroidal anti-inflammatories", "Non-steroidal anti-inflammatories"),
        ("Intravenous contrast dye", "Intravenous contrast dye"),
        ("Local anesthetics", "Local anesthetics"),
        ("Pollen", "Pollen"),
        ("Cat", "Cat"),
        ("Dog", "Dog"),
        ("Insect sting", "Insect sting"),
        ("Mold", "Mold"),
        ("Perfume", "Perfume"),
        ("Cosmetics", "Cosmetics"),
        ("Semen", "Semen"),

easy_healthcare/healthpass/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("first_name", "last_name", "email") + UserCreationForm.Meta.fields

class CustomLoginForm(forms.Form):
    username_or_email = forms.CharField(max_length=300)
    password = forms.CharField(widget=forms.PasswordInput)

easy_healthcare/healthpass/templates/healthpass/bloodwork_deletelist.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Delete Read Blood Work</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static './styles/bloodwork_deletelist.css' %}">
        <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
        <script src="https://cdn.lordicon.com/lordicon.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
    </head>
    <body>
        <div class="container">
            <div class="sidebar">
                <lord-icon src="https://cdn.lordicon.com/usownftb.json" trigger="hover">
                </lord-icon>  
            </div>
            <div class="main-content">
                <h1><strong>Blood Work Data</strong></h1>
                {% if bloodwork_list %}
                    {% include 'healthpass/messages.html' %}
                {% else %}
                    {% include 'healthpass/messages.html' %}
                    <div class="error-home">
                        <p class="button1">
                            <a href="{% url 'health:user_home' %}">Home</a>
                        </p>
                    </div>
                {% endif %}
                <div>
                    {% for bloodwork in bloodwork_list %}
                        <div class="bloodwork-item">
                            <ul>
                                <li><strong>Hb Genotype:</strong> {{ bloodwork.hb_genotype }}<br></li>
                                <li><strong>Sickling Test:</strong> {{ bloodwork.sickling_test }}<br></li>
                                <li><strong>Blood Group:</strong> {{ bloodwork.blood_group }}<br></li>
                                <li><strong>Malaria Parasite:</strong> {{ bloodwork.malaria_parasite }}<br></li>
                                <li><strong>Hepatitis A:</strong> {{ bloodwork.hepatitis_a }}<br></li>
                                <li><strong>Hepatitis B:</strong> {{ bloodwork.hepatitis_b }}<br></li>
                                <li><strong>HIV:</strong> {{ bloodwork.hiv }}<br></li>
                                <li><strong>VDRL:</strong> {{ bloodwork.vdrl }}<br></li>
                                <li><strong>H.pylori:</strong> {{ bloodwork.hpylori }}<br></li>
                                <li><strong>Rhesus Antigen:</strong> {{ bloodwork.rhesus_antigen }}<br></li>
                            </ul>
                        </div>
                        <div class="buttons">
                            <p class="button2">
                                <a href="{% url 'health:blood_work_delete' bloodwork.id %}">
                                    delete bloodwork {{ bloodwork.id }}
                                </a>
                            </p>
                            <p class="button1">
                                <a href="{% url 'health:user_home' %}">Home</a>
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div> 
        </div>
    </body>
</html>

easy_healthcare/healthpass/templates/healthpass/custom_home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Health Practitioner Page</title>
        <meta charset="utf-8">
        <script src="https://cdn.tailwindcss.com"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
        <link rel="stylesheet" href="{% static './styles/custom_home.css' %}">
        <!-- <style>
            nav {
                display: flex;
                flex-direction: row;
                justify-content: space-around;
                height: inherit;
                width: inherit;
            }
        </style> -->
    </head>
    <body>
        <main>
            {% include 'healthpass/messages.html' %}
            <div class="main-div">
                <h1>Welcome to the Custom Health Practitioner Page</h1>
                <p class="Practitioner">Hello, Health Practitioner, {{ custom_logged_user.first_name }} {{ custom_logged_user.last_name }}</p>
            </div>
        </main>
        <nav>
            <div class="">
                <img src="{% static './images/loading2.png' %}" alt="health" class="logo">
            </div>
        </nav>
        <section class="checking">
            <div class="grid">
                <!-- Add the read blood, urinal analysis, and general info links here. -->
                <div>
                    <a href="{% url 'health:custom_blood_work_read' %}" class="blood-works">check blood works</a>
                </div>
                <div class="">
                    <a href="{% url 'health:custom_general_info_read' %}" class="general-infos">check general infos</a>
                </div>
                <div class="">
                    <a href="{% url 'health:custom_urinalysis_read' %}" class="urinalysis">check urinalysis</a>
                </div>
                <div class="">
                    <a href="{% url 'health:custom_logout' %}" class="log-out">Log out</a>
                </div>
            </div>
        </section>
    </body>
</html>

easy_healthcare/healthpass/templates/healthpass/custom_password_reset_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Custom Password Reset</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static './styles/custom_password_reset_form.css' %}" type="text/css">
    <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
</head>

<body>
    <div class="form-container">
        <h2>Forgot Password</h2>
        {% if custom_password_reset_form.errors %}
        <div>
            <p>The email address is not properly written :(</p>
        </div>
        {% endif %}
        <div>
            {% load crispy_forms_tags %}
            <form method="post" action="">
                {% csrf_token %}
                {{ custom_password_reset_form|crispy }}
                <p>
                    <label style="display: none;" for="custom_password_reset_submit"></label>
                    <input style="display: none;" id="custom_password_reset_submit" type="submit"
                        name="custom_password_reset_submit" value="custom_password">
                </p>
                <p>
                    <button id="submit_custom_password_reset" type="button">Submit Confirmation Email Address</button>
                </p>
            </form>
        </div>
    </div>
    <div>
        <p>
            <a href="{% url 'health:custom_login' %}" class="back-link">
                Back to Login
            </a>
        </p>
    </div>
</body>
<script>
    const CustomButton = document.querySelector("#submit_custom_password_reset");
    const CustomSubmit = document.querySelector("#custom_password_reset_submit");
    CustomSubmit.addEventListener("click", () => {
        console.log("submitting email confirmation for custom password reset");
    });
    CustomButton.addEventListener("click", () => {
        CustomSubmit.click();
    });
</script>
</div>
</body>

</html>

easy_healthcare/healthpass/templates/healthpass/custom_user.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Secure Sign up</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
        <link rel="stylesheet" href="{% static './styles/custom_user.css' %}" type="text/css">
    </head>
    <body>
        {% if customuser_form.errors %}
            <div class="Error">
                <p>{{ error_message_1 }}</p>
            </div>
        {% endif %}
        {% if error_message %}
            <div class="Error">
                <p>{{ error_message }}</p>
            </div>
        {% endif %}
        <div class="form-container">
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'health:custom_signup' %}">
                {% csrf_token %}
                {{ customuser_form|crispy }}
                <p>
                    <label style="display: none;" for="custom_signup"></label>
                    <input style="display: none;" id="custom_signup" type="submit" name="custom_signup" value="signup">
                </p>
                <p class="signup_button">
                    <button id="signup_custom" type="button">Sign Up</button>
                </p>
                <div class="as_account">
                    <div>
                        <p>Already have an account?</p>
                    </div>
                    <div class="div_login">
                        <p>
                            <a href="{% url 'health:custom_login' %}">Sign in</a>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </body>
    <script>
        const CustomButton = document.querySelector("#signup_custom");
        const CustomSubmit = document.querySelector("#custom_signup");

        CustomSubmit.addEventListener("click", () => {
            console.log("submitting custom sigup data...");
        });
        CustomButton.addEventListener("click", () => {
            CustomSubmit.click();
        });
    </script>
</html>

easy_healthcare/healthpass/templates/healthpass/generalinfo_updatelist.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Update Read General Info</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="{% static './styles/generalinfo_updatelist.css' %}">
        <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
    </head>
    <body>
        <div class="container">
            <div class="sidebar">
                <img src="../../static/images/doctor.png" alt="doctor image">
            </div>

            <div class="main-content">
                <h1><strong>General Information</strong></h1>
                {% if generalinfo_list %}
                    {% include 'healthpass/messages.html' %}
                {% else %}
                    {% include 'healthpass/messages.html' %}
                    <div class="error-home">
                        <p class="button1">
                            <a href="{% url 'health:user_home' %}">Home</a>
                        </p>
                    </div>
                {% endif %}
                <div class="generalinfo-list">
                    {% for generalinfo in generalinfo_list %}
                        <div class="generalinfo-item">
                            <ul>
                                <li><strong>Gender:</strong> {{ generalinfo.gender }}<br></li>
                                <li><strong>Country:</strong> {{ generalinfo.country }}<br></li>
                                <li><strong>Passport Number:</strong> {{ generalinfo.passport_number }}<br></li>
                                <li><strong>Date of Birth:</strong> {{ generalinfo.date_of_birth }}<br></li>
                                <li><strong>Weight:</strong> {{ generalinfo.weight }}<br></li>
                                <li><strong>Name of Emergency Contact:</strong> {{ generalinfo.name_of_emergency_contact }}<br></li>
                                <li><strong>Relationship:</strong> {{ generalinfo.relationship }}<br></li>
                                <li><strong>Email of Emergency Contact:</strong> {{ generalinfo.email_of_emergency_contact }}<br></li>
                                <li><strong>Phone Number of Emergency Contact:</strong> {{ generalinfo.phone_number_of_emergency_contact }}<br></li>
                                    {% for immunization in generalinfo.immunizations.all %}
                                        <li><strong>Immunization{{ immunization.id }}:</strong> {{ immunization.immunization }}<br></li>
                                    {% endfor %}
                                    {% for allergy in generalinfo.allergies.all %}
                                        <li><strong>Allergy{{ allergy.id }}:</strong> {{ allergy.allergy }}<br></li>
                                    {% endfor %}
                            </ul>
                        </div>
                        <div class="buttons">
                            <p>
                                <a href="{% url 'health:user_home' %}">Home</a>
                            </p>
                            <p>
                                <a href="{% url 'health:general_info_update' generalinfo.id %}">
                                    update generalinfo {{ generalinfo.id }}
                                </a>
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
    <script>
    </script>
</html>

easy_healthcare/healthpass/templates/healthpass/logged_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loading Page</title>
    <link rel="stylesheet" href="{% static './styles/load.css' %}">
    <link rel="icon" type="image/png" href="{% static './images/loading1.png' %}">
</head>
<body>
    <!-- THE LOADING PAGE -->
    <div id="loading">
        <img src="{% static './images/loading1.png' %}" alt="Loading logo 1" id="loading-logo">
    </div>

    <!-- Second Page -->
    <div id="loading1" style="display: none;">
        <img src="{% static './images/loading2.png' %}" alt="loading logo 2" id="loading-logo2">
    </div>

    <script src="{% static './scripts/load.js' %}"></script>
</body>
</html>